ghost:
  image:
    repository: ghost
    tag: "5.110.4"  # Use the exact Ghost version
    pullPolicy: IfNotPresent
  env:
    database:
      client: mysql
      connection: mysql://root:password@mysql:3306/ghostdb
  persistence:
    enabled: true
    storageClass: "standard"
    accessMode: ReadWriteOnce
    size: 20Gi

mysql:
  image:
    repository: mysql
    tag: "8.0.41"  # Latest stable MySQL 8.0 compatible with Ghost
    pullPolicy: IfNotPresent
  rootPassword: password
  database: ghostdb
  persistence:
    enabled: true
    storageClass: "standard"
    accessMode: ReadWriteOnce
    size: 20Gi
