apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # Retain data even after the PVC is deleted
  storageClassName: "{{ .Values.ghost.persistence.storageClass }}"
  hostPath:
    path: /mnt/data/ghost  # You can change this to a different path for your setup
