apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: "{{ .Values.ghost.image.repository }}:{{ .Values.ghost.image.tag }}"
          env:
            - name: DATABASE_URL
              value: mysql://root:password@mysql:3306/ghostdb
          volumeMounts:
            - name: ghost-data
              mountPath: /var/lib/ghost/content
      volumes:
        - name: ghost-data
          persistentVolumeClaim:
            claimName: ghost-pvc
