apiVersion: v1
kind: Service
metadata:
  name: ghost
  namespace: ghost-blog
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "elb"  # ELB (default AWS Classic Load Balancer)
spec:
  type: LoadBalancer
  selector:
    app: ghost
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2368  # Ensure this is the correct Ghost container port
