apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # Retain data even after the PVC is deleted
  storageClassName: standard  # Change this based on your cluster setup
  hostPath:
    path: /mnt/data/ghost  # You can change this to a different path for your setup
