apiVersion: v1
kind: Service
metadata:
  name: ghost
  namespace: ghost-blog
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # ✅ Switch to NLB
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: "eipalloc-02e41f35d082f387b"  # ✅ Replace with your EIP Allocation IDs
spec:
  type: LoadBalancer
  selector:
    app: ghost
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2368  # Ensure this is Ghost's container port
