apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-pvc
  labels:
    app: ghost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "gp2"  # Adjust based on your Kubernetes environment

